#sudo: false

os:
 - linux

env:
 global:
  - LD_LIBRARY_PATH: /usr/local/lib

language: cpp

branches:
 only:
  - stable
  - malisz
  - dura

compiler:
 - gcc
 - clang

install:
 # SDL2
 - wget http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
 - tar -zxvf SDL2-2.0.3.tar.gz
 - cd SDL2-2.0.3
 - ./configure && make && sudo make install
 - cd -
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install g++-5
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
# - alias g++ g++4.8

# addons:
#  apt:
#   packages:
#    - libsdl2
#    - g++-4.8
#   sources:
#    - ubuntu-toolchain-r-test
#    - zoogie/sdl2-snapshots
   
# before_install:
#  - alias g++=g++-4.8









