os:
 - linux
language: cpp
branches:
  only:
    - stable
    - dura

compiler:
 - gcc
 - clang
 
before_install:
 - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsdl2
