sudo: false

os:
 - linux
language: cpp
branches:
  only:
    - stable
    - dura

compiler:
 - gcc
 - clang

addons:
 apt:
  packages:
   - libsdl2-dev
   - g++-4.8
  sources:
   - ubuntu-toolchain-r-test
   
   before_install:
    - alias g++=g++-4.8
